-- MIGRATION: Boteco PDF Menu
-- Run this in Supabase SQL Editor

-- Clear existing data
delete from menu_items;
delete from menu_categories;

-- 1. Menu Categories
insert into menu_categories (name_pt, name_fr, name_en, slug, sort_order) values
('Entradas', 'Entrées', 'Starters', 'entrees', 1),
('Pratos Principais', 'Plats Principaux', 'Main Courses', 'plats', 2),
('Sobremesas', 'Desserts', 'Desserts', 'desserts', 3),
('Bebidas', 'Boissons', 'Drinks', 'bebidas', 4);

-- 2. Menu Items (38 total)
insert into menu_items (category_id, name_pt, name_fr, name_en, description_pt, description_fr, description_en, price, image_url, badge_pt, badge_fr, badge_en, featured, portion, tagline_pt, tagline_fr, tagline_en, sort_order, active) values
((select id from menu_categories where slug = 'entrees'), 'Coxinha', 'Coxinha', 'Coxinha', 'Croquete de frango marinado, massa dourada e crocante.', 'Croquette de poulet mariné, pâte dorée et croustillante.', 'Marinated chicken croquette, golden and crispy dough.', 13, 'https://images.unsplash.com/photo-1700353763351-cb61036f3232?w=800&q=80&fit=crop&auto=format', 'Favorito', 'Favori', 'Favorite', true, null, null, null, null, 0, true),
((select id from menu_categories where slug = 'entrees'), 'Pastel Brasileiro (Queijo / Frango / Carne)', 'Pastel Brésilien (Fromage / Poulet / Boeuf)', 'Brazilian Pastel (Cheese / Chicken / Beef)', 'Pastel frito na hora, recheado com queijo, frango ou carne moída.', 'Pastel frit à la commande, farci au fromage, poulet ou boeuf haché.', 'Fried pastel made to order, filled with cheese, chicken or ground beef.', 13, null, null, null, null, true, null, null, null, null, 1, true),
((select id from menu_categories where slug = 'entrees'), 'Pão de Queijo', 'Pão de Queijo', 'Cheese Bread', 'Pão de queijo mineiro tradicional, macio por dentro e crocante por fora.', 'Petit pain brésilien au fromage, moelleux à l''intérieur et croustillant à l''extérieur.', 'Traditional Brazilian cheese bread, soft inside and crispy outside.', 12, 'https://images.unsplash.com/photo-1773399159824-5a63848662d2?w=800&q=80&fit=crop&auto=format', null, null, null, true, null, null, null, null, 2, true),
((select id from menu_categories where slug = 'entrees'), 'Bolinho de Queijo', 'Bolinho de Queijo', 'Cheese Croquette', 'Bolinho crocante, recheio de queijo derretido.', 'Boulette croustillante, farce de fromage fondant.', 'Crispy croquette with melted cheese filling.', 13, null, null, null, null, false, null, null, null, null, 3, true),
((select id from menu_categories where slug = 'entrees'), 'Calabresa Acebolada', 'Calabresa Acebolada', 'Grilled Calabrese Sausage', 'Linguiça calabresa grelhada com cebolas caramelizadas.', 'Saucisse calabrese grillée, oignons caramélisés.', 'Grilled Calabrese sausage with caramelized onions.', 17, null, null, null, null, false, null, null, null, null, 4, true),
((select id from menu_categories where slug = 'entrees'), 'Torresmo', 'Torresmo', 'Fried Pork Rinds', 'Couro de porco frito, crocante por fora, macio por dentro.', 'Couenne de porc frite, croustillante à l''extérieur.', 'Fried pork rinds, crispy on the outside.', 16, null, null, null, null, false, null, null, null, null, 5, true),
((select id from menu_categories where slug = 'entrees'), 'Camarão Empanado (6)', 'Crevettes Panées (6)', 'Breaded Shrimp (6)', 'Camarões empanados e fritos, servidos com molho.', 'Crevettes panées et frites, servies avec sauce.', 'Breaded and fried shrimp, served with dipping sauce.', 18, 'https://images.unsplash.com/photo-1582993728648-1f29c748e5ad?w=800&q=80&fit=crop&auto=format', null, null, null, false, null, null, null, null, 6, true),
((select id from menu_categories where slug = 'entrees'), 'Asa de Frango (6)', 'Ailes de Poulet (6)', 'Chicken Wings (6)', 'Asas de frango temperadas e fritas.', 'Ailes de poulet assaisonnées et frites.', 'Seasoned and fried chicken wings.', 18, 'https://images.unsplash.com/photo-1571162437205-8889ff2fee26?w=800&q=80&fit=crop&auto=format', null, null, null, false, null, null, null, null, 7, true),
((select id from menu_categories where slug = 'entrees'), 'Batata Frita', 'Frites', 'French Fries', 'Batatas fritas crocantes, temperadas na hora.', 'Frites croustillantes, assaisonnées sur commande.', 'Crispy french fries, seasoned to order.', 8, 'https://images.unsplash.com/photo-1630431341973-02e1b662ec35?w=800&q=80&fit=crop&auto=format', null, null, null, false, null, null, null, null, 8, true),
((select id from menu_categories where slug = 'plats'), 'Picanha', 'Picanha', 'Picanha Steak', 'Picanha grelhada na brasa, servida com fritas, farofa e vinagrete.', 'Picanha grillée au feu de bois, servie avec frites, farofa et vinaigrette.', 'Flame-grilled picanha steak, served with fries, farofa and vinaigrette.', 28, 'https://images.unsplash.com/photo-1558030137-a56c1b004fa3?w=800&q=80&fit=crop&auto=format', 'Grelhado na brasa', 'Grillé au feu de bois', 'Flame-grilled', true, null, 'O corte nobre do Brasil', 'La coupe noble du Brésil', 'Brazil''s premium cut', 9, true),
((select id from menu_categories where slug = 'plats'), 'Espeto de Frango', 'Brochette de Poulet', 'Chicken Skewer', 'Espeto de frango grelhado, servido com fritas, farofa e vinagrete.', 'Brochette de poulet grillé, servie avec frites, farofa et vinaigrette.', 'Grilled chicken skewer, served with fries, farofa and vinaigrette.', 18, null, null, null, null, false, null, null, null, null, 10, true),
((select id from menu_categories where slug = 'plats'), 'Coração de Frango', 'Cœur de Poulet', 'Chicken Heart Skewer', 'Espeto de coração de frango grelhado, servido com fritas, farofa e vinagrete.', 'Brochette de cœurs de poulet grillés, servie avec frites, farofa et vinaigrette.', 'Grilled chicken heart skewer, served with fries, farofa and vinaigrette.', 17, null, null, null, null, false, null, null, null, null, 11, true),
((select id from menu_categories where slug = 'plats'), 'Queijo Coalho Grelhado', 'Queijo Coalho Grillé', 'Grilled Coalho Cheese', 'Queijo coalho grelhado importado do Brasil.', 'Fromage grillé importé du Brésil.', 'Grilled cheese imported from Brazil.', 20, null, null, null, null, false, null, null, null, null, 12, true),
((select id from menu_categories where slug = 'bebidas'), 'Caipirinha', 'Caipirinha', 'Caipirinha', 'Cachaça, limão, açúcar e gelo. Verre $7 / Pichet $20.', 'Cachaça, lime, sucre et glace. Verre 7$ / Pichet 20$.', 'Cachaça, lime, sugar and ice. Glass $7 / Pitcher $20.', 7, 'https://images.unsplash.com/photo-1644809818228-e29aa5aa8151?w=800&q=80&fit=crop&auto=format', 'Clássico', 'Classique', 'Classic', true, null, null, null, null, 13, true),
((select id from menu_categories where slug = 'bebidas'), 'Caipiroska', 'Caipiroska', 'Caipiroska', 'Vodka, morangos, limão, açúcar e gelo. Verre $9 / Pichet $25.', 'Vodka, fraises, lime, sucre et glace. Verre 9$ / Pichet 25$.', 'Vodka, strawberries, lime, sugar and ice. Glass $9 / Pitcher $25.', 9, 'https://images.unsplash.com/photo-1581927692308-be9e43b4d860?w=800&q=80&fit=crop&auto=format', null, null, null, true, null, null, null, null, 14, true),
((select id from menu_categories where slug = 'bebidas'), 'Sakerinha', 'Sakerinha', 'Sakerinha', 'Saquê, morangos ou limão, açúcar e gelo. Verre $9.50 / Pichet $27.', 'Saké, fraises ou lime, sucre et glace. Verre 9,50$ / Pichet 27$.', 'Sake, strawberries or lime, sugar and ice. Glass $9.50 / Pitcher $27.', 9.5, null, null, null, null, false, null, null, null, null, 15, true),
((select id from menu_categories where slug = 'bebidas'), 'Rio Sunset', 'Rio Sunset', 'Rio Sunset', 'Curaçau, suco de laranja e folhas de hortelã. Verre $9.50 / Pichet $27.', 'Curaçao, jus d''orange et feuilles de menthe. Verre 9,50$ / Pichet 27$.', 'Curaçao, orange juice and mint leaves. Glass $9.50 / Pitcher $27.', 9.5, null, null, null, null, false, null, null, null, null, 16, true),
((select id from menu_categories where slug = 'bebidas'), 'Xeque-Mate', 'Xeque-Mate', 'Xeque-Mate', 'Cachaça, mate, guaraná e suco de limão. Verre $11 / Pichet $31.', 'Cachaça, maté, guaraná et jus de lime. Verre 11$ / Pichet 31$.', 'Cachaça, mate, guaraná and lime juice. Glass $11 / Pitcher $31.', 11, null, null, null, null, false, null, null, null, null, 17, true),
((select id from menu_categories where slug = 'bebidas'), 'Amazônia', 'Amazônia', 'Amazônia', 'Cachaça, frutas vermelhas, limão, açúcar e gelo. Verre $11 / Pichet $31.', 'Cachaça, fraises ou lime, sucre et glace. Verre 11$ / Pichet 31$.', 'Cachaça, berries, lime, sugar and ice. Glass $11 / Pitcher $31.', 11, null, null, null, null, false, null, null, null, null, 18, true),
((select id from menu_categories where slug = 'bebidas'), 'Matsunaga', 'Matsunaga', 'Matsunaga', 'Coquetel especial da casa.', 'Cocktail spécial de la maison.', 'House special cocktail.', 13, null, null, null, null, false, null, null, null, null, 19, true),
((select id from menu_categories where slug = 'bebidas'), 'Borogodó', 'Borogodó', 'Borogodó', 'Cachaça, tequila, suco de laranja, grenadina.', 'Cachaça, tequila, jus d''orange, grenadine.', 'Cachaça, tequila, orange juice, grenadine.', 15, null, null, null, null, true, null, null, null, null, 20, true),
((select id from menu_categories where slug = 'bebidas'), 'Caipirinha Tradicional com Corona', 'Caïpirinha Trad. Servie avec Corona', 'Traditional Caipirinha with Corona', 'Caipirinha tradicional servida com uma Corona invertida.', 'Caïpirinha trad. servie avec une Corona renversée.', 'Traditional Caipirinha served with an inverted Corona.', 8, null, null, null, null, true, null, null, null, null, 21, true),
((select id from menu_categories where slug = 'bebidas'), 'Corona Extra', 'Corona Extra', 'Corona Extra', 'Cerveja mexicana clara.', 'Bière mexicaine blonde.', 'Mexican lager.', 9.5, 'https://images.unsplash.com/photo-1608742598121-15038a8db33c?w=800&q=80&fit=crop&auto=format', null, null, null, true, null, null, null, null, 22, true),
((select id from menu_categories where slug = 'bebidas'), 'Corona Zero', 'Corona Zero', 'Corona Zero', 'Versão sem álcool da Corona.', 'Version sans alcool de la Corona.', 'Non-alcoholic version of Corona.', 8.5, null, null, null, null, false, null, null, null, null, 23, true),
((select id from menu_categories where slug = 'bebidas'), 'Balde Corona (5)', 'Bucket Corona (5)', 'Corona Bucket (5)', 'Balde com 5 Coronas.', 'Seau de 5 Coronas.', 'Bucket of 5 Coronas.', 38, null, null, null, null, false, null, null, null, null, 24, true),
((select id from menu_categories where slug = 'bebidas'), 'Labatt 50', 'Labatt 50', 'Labatt 50', 'Cerveja canadense clássica.', 'Bière canadienne classique.', 'Classic Canadian beer.', 8, null, null, null, null, false, null, null, null, null, 25, true),
((select id from menu_categories where slug = 'bebidas'), 'Michelob Ultra', 'Michelob Ultra', 'Michelob Ultra', 'Cerveja leve e refrescante.', 'Bière légère et rafraîchissante.', 'Light and refreshing beer.', 5, null, null, null, null, false, null, null, null, null, 26, true),
((select id from menu_categories where slug = 'bebidas'), 'Belle Mer', 'Belle Mer', 'Belle Mer', 'Cerveja artesanal canadense.', 'Bière artisanale canadienne.', 'Canadian craft beer.', 3.5, null, null, null, null, false, null, null, null, null, 27, true),
((select id from menu_categories where slug = 'bebidas'), 'Chipie', 'Chipie', 'Chipie', 'Cerveja artesanal local.', 'Bière artisanale locale.', 'Local craft beer.', 3.5, null, null, null, null, false, null, null, null, null, 28, true),
((select id from menu_categories where slug = 'bebidas'), 'Modelo', 'Modelo', 'Modelo', 'Cerveja mexicana tradicional.', 'Bière mexicaine traditionnelle.', 'Traditional Mexican beer.', 3.5, null, null, null, null, false, null, null, null, null, 29, true),
((select id from menu_categories where slug = 'bebidas'), 'Stella Artois', 'Stella Artois', 'Stella Artois', 'Cerveja belga premium.', 'Bière belge premium.', 'Premium Belgian beer.', 5, null, null, null, null, false, null, null, null, null, 30, true),
((select id from menu_categories where slug = 'bebidas'), 'Cidre / Lacroix Rosé', 'Cidres / Lacroix Rosé', 'Cider / Lacroix Rosé', 'Cidre ou Lacroix Rosé.', 'Cidre ou Lacroix Rosé.', 'Cider or Lacroix Rosé.', 9.5, null, null, null, null, false, null, null, null, null, 31, true),
((select id from menu_categories where slug = 'bebidas'), 'Água com Gás', 'Eau Petillante', 'Sparkling Water', 'Água mineral com gás.', 'Eau minérale gazeuse.', 'Sparkling mineral water.', 5, null, null, null, null, false, null, null, null, null, 32, true),
((select id from menu_categories where slug = 'bebidas'), 'Guaraná', 'Guaraná', 'Guaraná', 'Refrigerante brasileiro de guaraná.', 'Soda brésilien au guarana.', 'Brazilian guaraná soda.', 5, null, null, null, null, true, null, null, null, null, 33, true),
((select id from menu_categories where slug = 'bebidas'), 'Coca-Cola', 'Coca-Cola', 'Coca-Cola', 'Refrigerante de cola.', 'Soda cola.', 'Cola soda.', 3.5, null, null, null, null, false, null, null, null, null, 34, true),
((select id from menu_categories where slug = 'bebidas'), 'Coca-Cola Zero', 'Coca-Cola Zero', 'Coca-Cola Zero', 'Refrigerante de cola sem açúcar.', 'Soda cola sans sucre.', 'Sugar-free cola soda.', 3.5, null, null, null, null, false, null, null, null, null, 35, true),
((select id from menu_categories where slug = 'bebidas'), 'Sprite', 'Sprite', 'Sprite', 'Refrigerante de limão.', 'Soda citron-lime.', 'Lemon-lime soda.', 3.5, null, null, null, null, false, null, null, null, null, 36, true),
((select id from menu_categories where slug = 'bebidas'), 'Suco de Laranja', 'Jus d''Orange', 'Orange Juice', 'Suco de laranja natural.', 'Jus d''orange frais.', 'Fresh orange juice.', 5, null, null, null, null, false, null, null, null, null, 37, true);
